name: pytest-pr-check
on:
  pull_request:
    branches: [main]
env:
  AWS_REGION : ${{ secrets.AWS_REGION }}
# permission can be added at job level or workflow level
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  Pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: ${{ secrets.SAMPLE_ROLE_SESSION }}
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  pytest
          pip install s3fs
          pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        env:
           ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
           SAMPLE_ROLE_SESSION: ${{ secrets.SAMPLE_ROLE_SESSION }}
           BUCKET_NAME_PYTEST: ${{ secrets.BUCKET_NAME_PYTEST }}
           GZ_BUCKET_NAME: ${{ secrets.GZ_BUCKET_NAME }}
           PYTEST_FLAG:  "True"
        run: |
           python --version
           pytest -rp
